### ISSUE TITLE
Need moar Static Shock references

### ISSUE THREAD

**Issue by jrf0110** [wesleytodd/rufio#2]
![http://2.bp.blogspot.com/-lQsBq0T8RkE/UBVlFbvgJhI/AAAAAAAAGIc/6irrHgrYZGM/s1600/Static_Shock_(TV_Series).jpg](http://2.bp.blogspot.com/-lQsBq0T8RkE/UBVlFbvgJhI/AAAAAAAAGIc/6irrHgrYZGM/s1600/Static_Shock_%28TV_Series%29.jpg)

**Comment by wesleytodd** [comment]
Haha, yeah that looks more like my little drawing than Rufio from Hook.  But then I'd have to change the name on npm.  Fork away.....
